name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - client
      - front
      - planner
      - tools

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./server

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: server

    - name: Run go test
      run: go test ./...
